//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Jamnik.cpp
//  @ Date : 26.02.2018
//  @ Author : 
//
//


#include "Jamnik.h"

int Jamnik::test4(int k) {
    k-=3;
	return k;
}

