//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pies.cpp
//  @ Date : 26.02.2018
//  @ Author : 
//
//


#include "Pies.h"

int Pies::test3(int z) {
    z*=2;
	return z;
}

