//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.cpp
//  @ Date : 26.02.2018
//  @ Author : 
//
//


#include "Ssak.h"

int Ssak::test2(int x) {
    x/=3;
	return x;
}

