//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TStudent.h
//  @ Date : 12.03.2018
//  @ Author : 
//
//


#if !defined(_TSTUDENT_H)
#define _TSTUDENT_H

#using <mscorlib.dll>

class TStudent {
public:
    TStudent();
    ~TStudent();
};

#endif  //_TSTUDENT_H
