//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TUniversity.cpp
//  @ Date : 12.03.2018
//  @ Author :
//
//


#include "TUniversity.h"
#using <mscorlib.dll>

void TUniversity::attach() {
    TStudent* stu = new TStudens[5];
    students.push(stu);
}

void TUniversity::detach() {
    for (it=students.begin(); it!=students.end(); it++){
        delete [] *it;
    }
}

