//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TLibrary.cpp
//  @ Date : 05.03.2018
//  @ Author :
//
//


#include "TLibrary.h"

TLibrary::TLibrary(const string& libName) {
    libraryName=libName;
    cout<<libName<<endl;
    book= new TBook;
}

TLibrary::~TLibrary() {
    delete book;
}

void TLibrary::printData() {
    cout<<book->getTitle()<<endl<<book->getShelfMark()<<endl;
}

void TLibrary::setData(string title, string mark) {
    book->setTitle(title);
    book->setShelfMark(mark);
}

