//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Bernoulli.h
//  @ Date : 19.03.2018
//  @ Author :
//
//


#if !defined(_BERNOULLI_H)
#define _BERNOULLI_H

#include "Newton.h"
#include "Potega.h"
#using <mscorlib.dll>

class Bernoulli {
public:
    void bernoulli(int k, int n, int p);
private:
    Newton pomNewton;
    Potega pomPotega;
    long double P;
    double q;
};

#endif  //_BERNOULLI_H
