//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Bernoulli.cpp
//  @ Date : 19.03.2018
//  @ Author :
//
//


#include "Bernoulli.h"
#include <iostream>

void Bernoulli::bernoulli(int k, int n, int p) {
    q=1-p;
    P=( pomNewton.newton(n,k)*pomPotega.potega(p,k)*pomPotega.potega(q,n-k) );
    cout<<P;
}

