//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Newton.h
//  @ Date : 19.03.2018
//  @ Author : 
//
//


#if !defined(_NEWTON_H)
#define _NEWTON_H

#include "Silnia.h"
#using <mscorlib.dll>

class Newton {
public:
    long double newton(int n, int k);
private:
    Silnia pomSilnia;
};

#endif  //_NEWTON_H
