//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Potega.cpp
//  @ Date : 19.03.2018
//  @ Author :
//
//


#include "Potega.h"

double Potega::potega(int n, int m) {

    if(m==0) return 1;
    else return n * potega(n, m - 1);

}

