//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Potega.h
//  @ Date : 19.03.2018
//  @ Author : 
//
//


#if !defined(_POTEGA_H)
#define _POTEGA_H

#using <mscorlib.dll>

class Potega {
public:
    double potega(int n, int m);
};

#endif  //_POTEGA_H
