//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Silnia.h
//  @ Date : 19.03.2018
//  @ Author : 
//
//


#if !defined(_SILNIA_H)
#define _SILNIA_H

#using <mscorlib.dll>

class Silnia {
public:
    double silnia(int n);
};

#endif  //_SILNIA_H
