//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Silnia.cpp
//  @ Date : 19.03.2018
//  @ Author :
//
//


#include "Silnia.h"
#using <mscorlib.dll>

double Silnia::silnia(int n) {

    if(n==0) return 1;
    else return n*silnia(n-1);

}

