//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TStudent.cpp
//  @ Date : 12.03.2018
//  @ Author :
//
//


#include "TStudent.h"
#using <mscorlib.dll>

TStudent::TStudent() {
    cout<<"Konstruktor TStudent"<<endl;
}

TStudent::~TStudent() {
    cout<<"Destruktor TStudent"<<endl;
}

void TStudent::setName(string name) {
    studentName=name;
}

string TStudent::getName() {
    return studentName;
}

void TStudent::setAge(int age) {
    studentAge=age;
}

int TStudent::getAge() {
    return studentAge;
}

