//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TUniversity.cpp
//  @ Date : 12.03.2018
//  @ Author :
//
//


#include "TUniversity.h"
#using <mscorlib.dll>

void TUniversity::attach(TStudent* st) {
    students.push_back(st);
}

void TUniversity::detach() {
    students.pop_back();
    if( students.empty() ) cout<<"Pusto"<<endl;
    else cout<<"Nie pusto"<<endl;
}

void TUniversity::printData(int i) {
    cout<<students[i]->getName()<<endl<<students[i]->getAge()<<endl;
}

void TUniversity::setData(int i, string name, int age) {
    students[i]->setName(name);
    students[i]->setAge(age);
}

